### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by JacksonDNC** [Paytm-Payments/Paytm_Magento_v1.x_Kit#1]
Hello There
We have uploaded app folder as per instruction after when we go on System->Configuration -> Sales->Payment it crashes to white page. in log get something like below.
PHP Fatal error:  Class 'One97_Paytm_Helper_Data' not found in /home1/example.com/public_html/app/Mage.php on line 547

**Comment by Mohit-Aggarwal1** [comment]
Kindly do the following

1. Clear cache ( System > Cache management )
2. If you are using compilation, disable it or run recompile ( System > Tools > Compilation )

please refer below link 
http://nwdthemes.com/2014/12/05/magento-module-fatal-error-helper-class-found

**Comment by JacksonDNC** [comment]
Thanks now its working
